name: Playwright UI Tests
on:
  push:
    branches:
      - main
      - master
      - refactor
      - 2024-refactoring-RF2
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  run-ui-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js '22.x'
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: npm install -g yarn && yarn
      - name: Build the project
        run: yarn build
      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
